# Generated by Django 5.1.6 on 2025-02-12 17:14

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import home.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
                'permissions': [('can_view_all_jobs', 'Can view all job listings'), ('can_edit_job', 'Can edit job listings')],
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, help_text='Enter the job title', max_length=200)),
                ('description', models.TextField(help_text='Provide a detailed description of the job')),
                ('job_type', models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('Internship', 'Internship'), ('Contract', 'Contract'), ('Freelance', 'Freelance')], default='Full-Time', help_text='Select the type of job', max_length=20)),
                ('image', models.ImageField(blank=True, help_text='Upload a relevant image', null=True, upload_to=home.models.upload_to)),
                ('location', models.CharField(db_index=True, help_text='Enter the job location', max_length=200)),
                ('vacancy', models.PositiveIntegerField(default=1, help_text='Enter the number of vacancies')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, help_text='Enter the salary range (optional)', max_digits=10, null=True)),
                ('responsibilities', models.TextField(help_text='List the job responsibilities')),
                ('qualifications', models.TextField(help_text='List the required qualifications')),
                ('benefits', models.TextField(help_text='List the job benefits')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('experience', models.CharField(help_text='Enter the required experience level', max_length=200)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Any', 'Any')], default='Any', help_text='Select the preferred gender (if applicable)', max_length=10)),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated slug for URLs', unique=True)),
                ('application_deadline', models.DateTimeField(blank=True, help_text='Set the application deadline', null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Closed', 'Closed'), ('Draft', 'Draft')], default='Draft', help_text='Select the job status', max_length=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The full name of the applicant.', max_length=50, verbose_name='Full Name')),
                ('email', models.EmailField(help_text='The email address of the applicant.', max_length=100, verbose_name='Email Address')),
                ('website', models.URLField(blank=True, help_text="Optional: The applicant's personal or portfolio website.", null=True, verbose_name='Personal Website')),
                ('cv', models.FileField(help_text='Upload your CV or resume in PDF or DOCX format.', upload_to='applications/cvs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx'])], verbose_name='CV/Resume')),
                ('cover_letter', models.TextField(help_text="A brief introduction and why you're a good fit for the job.", max_length=500, verbose_name='Cover Letter')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The date and time when the application was submitted.', verbose_name='Application Date')),
                ('job', models.ForeignKey(help_text='The job this application is for.', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='home.home', verbose_name='Job Applied For')),
            ],
            options={
                'verbose_name': 'Job Application',
                'verbose_name_plural': 'Job Applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
