# Generated by Django 5.1.6 on 2025-02-10 22:07

import django.db.models.deletion
import job.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, help_text='Enter the job title', max_length=200)),
                ('description', models.TextField(help_text='Provide a detailed description of the job')),
                ('job_type', models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('Internship', 'Internship'), ('Contract', 'Contract'), ('Freelance', 'Freelance')], default='Full-Time', help_text='Select the type of job', max_length=20)),
                ('image', models.ImageField(blank=True, help_text='Upload a relevant image', null=True, upload_to=job.models.upload_to)),
                ('location', models.CharField(db_index=True, help_text='Enter the job location', max_length=200)),
                ('vacancy', models.PositiveIntegerField(default=1, help_text='Enter the number of vacancies')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, help_text='Enter the salary range (optional)', max_digits=10, null=True)),
                ('responsibilities', models.TextField(help_text='List the job responsibilities')),
                ('qualifications', models.TextField(help_text='List the required qualifications')),
                ('benefits', models.TextField(help_text='List the job benefits')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(db_index=True, help_text='Enter the job category', max_length=200)),
                ('experience', models.CharField(help_text='Enter the required experience level', max_length=200)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Any', 'Any')], default='Any', help_text='Select the preferred gender (if applicable)', max_length=10)),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated slug for URLs', unique=True)),
                ('application_deadline', models.DateTimeField(blank=True, help_text='Set the application deadline', null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Closed', 'Closed'), ('Draft', 'Draft')], default='Draft', help_text='Select the job status', max_length=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Listing',
                'verbose_name_plural': 'Job Listings',
                'ordering': ['-published_at'],
                'permissions': [('can_view_all_jobs', 'Can view all job listings'), ('can_edit_job', 'Can edit job listings')],
            },
        ),
    ]
