# Generated by Django 5.1.6 on 2025-02-10 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_category_alter_job_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'permissions': [('can_view_all_jobs', 'Can view all job listings'), ('can_edit_job', 'Can edit job listings')], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={},
        ),
    ]
