# Generated by Django 5.1.6 on 2025-02-11 19:04

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_alter_category_options_alter_job_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The full name of the applicant.', max_length=50, verbose_name='Full Name')),
                ('email', models.EmailField(help_text='The email address of the applicant.', max_length=100, verbose_name='Email Address')),
                ('website', models.URLField(blank=True, help_text="Optional: The applicant's personal or portfolio website.", null=True, verbose_name='Personal Website')),
                ('cv', models.FileField(help_text='Upload your CV or resume in PDF or DOCX format.', upload_to='applications/cvs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx'])], verbose_name='CV/Resume')),
                ('cover_letter', models.TextField(help_text="A brief introduction and why you're a good fit for the job.", max_length=500, verbose_name='Cover Letter')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The date and time when the application was submitted.', verbose_name='Application Date')),
                ('job', models.ForeignKey(help_text='The job this application is for.', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='job.job', verbose_name='Job Applied For')),
            ],
            options={
                'verbose_name': 'Job Application',
                'verbose_name_plural': 'Job Applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
